#include <stdio.h>

#include "matrix.h"
#include "patterns.h"
#include "pgm_utils.h"
#include "utils.h"

#define PGM_FILE "./tests/lena.pgm"

int next_frame = 0;

int main()
{
	matrix_t *img;
	matrix_t *grid;

	img = read_pgm_file(PGM_FILE);
	write_pgm_file("./tests/img.pgm", img, "Generated by pgm_test");

	grid = get_resized_matrix(img, N_ROWS, N_COLS);
	write_pgm_file("./tests/grid_resized.pgm", grid, "Generated by pgm_test");

	center_matrix(grid);
	write_pgm_file("./tests/grid_centered.pgm", grid, "Generated by pgm_test");

	threshold_matrix(grid);
	write_pgm_file("./tests/grid_threshold.pgm", grid, "Generated by pgm_test");

	return 0;
}